version: 0.2
# phases:
#   install:
#     runtime-versions:
#       java: corretto8
#   # pre_build:
#   #   commands:
#   #     - echo Nothing to do in the pre_build phase...
#   build:
#     commands: 
#   #    - echo "Entering the build stage"
#       - cd mvc-project-1 && mvn clean install
#   # post_build:
#   #   commands:
#   #     - echo "Entering the post-build stage"
# artifacts:
#   files:
#     - '**/*'
phases:
  install:
    runtime-versions:
      docker: 18
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - $(aws ecr get-login --no-include-email --region $AWS_DEFAULT_REGION)
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...  
      - cd mvc-project-1    
      - docker build -t $IMAGE_REPO_NAME:$IMAGE_TAG .
      - docker tag $IMAGE_REPO_NAME:$IMAGE_TAG $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:$IMAGE_TAG      
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:$IMAGE_TAG