version: 0.2
phases:
  install:
    runtime-versions:
      java: corretto8
  # pre_build:
  #   commands:
  #     - echo Nothing to do in the pre_build phase...
  build:
    commands: 
  #    - echo "Entering the build stage"
      - mvc-project-1/./mvnw clean install
  # post_build:
  #   commands:
  #     - echo "Entering the post-build stage"
artifacts:
  files:
    - '**/*'