version: 0.2
phases:
  install:
    runtime-versions:
      java: corretto8
  pre_build:
    commands:
      - echo Nothing to do in the pre_build phase...
  build:
    commands: 
      - echo "Entering the build stage"
      - cd mvc-project-1
      - mvn clean install
  post_build:
    commands:
      - echo "Entering the post-build stage"
artifacts:
  files:
    - mvc-project-1/target/mvc-0.0.1-SNAPSHOT.jar